/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriveUploadIndexRouteImport } from './routes/drive/upload/index'
import { Route as DriveManageIndexRouteImport } from './routes/drive/manage/index'

const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveUploadIndexRoute = DriveUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => DriveRoute,
} as any)
const DriveManageIndexRoute = DriveManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => DriveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drive': typeof DriveRouteWithChildren
  '/drive/manage': typeof DriveManageIndexRoute
  '/drive/upload': typeof DriveUploadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drive': typeof DriveRouteWithChildren
  '/drive/manage': typeof DriveManageIndexRoute
  '/drive/upload': typeof DriveUploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drive': typeof DriveRouteWithChildren
  '/drive/manage/': typeof DriveManageIndexRoute
  '/drive/upload/': typeof DriveUploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drive' | '/drive/manage' | '/drive/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drive' | '/drive/manage' | '/drive/upload'
  id: '__root__' | '/' | '/drive' | '/drive/manage/' | '/drive/upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriveRoute: typeof DriveRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/upload/': {
      id: '/drive/upload/'
      path: '/upload'
      fullPath: '/drive/upload'
      preLoaderRoute: typeof DriveUploadIndexRouteImport
      parentRoute: typeof DriveRoute
    }
    '/drive/manage/': {
      id: '/drive/manage/'
      path: '/manage'
      fullPath: '/drive/manage'
      preLoaderRoute: typeof DriveManageIndexRouteImport
      parentRoute: typeof DriveRoute
    }
  }
}

interface DriveRouteChildren {
  DriveManageIndexRoute: typeof DriveManageIndexRoute
  DriveUploadIndexRoute: typeof DriveUploadIndexRoute
}

const DriveRouteChildren: DriveRouteChildren = {
  DriveManageIndexRoute: DriveManageIndexRoute,
  DriveUploadIndexRoute: DriveUploadIndexRoute,
}

const DriveRouteWithChildren = DriveRoute._addFileChildren(DriveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriveRoute: DriveRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
