/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriveIndexRouteImport } from './routes/drive/index'
import { Route as DriveUploadIndexRouteImport } from './routes/drive/upload/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveIndexRoute = DriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveUploadIndexRoute = DriveUploadIndexRouteImport.update({
  id: '/drive/upload/',
  path: '/drive/upload/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drive': typeof DriveIndexRoute
  '/drive/upload': typeof DriveUploadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drive': typeof DriveIndexRoute
  '/drive/upload': typeof DriveUploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drive/': typeof DriveIndexRoute
  '/drive/upload/': typeof DriveUploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drive' | '/drive/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drive' | '/drive/upload'
  id: '__root__' | '/' | '/drive/' | '/drive/upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriveIndexRoute: typeof DriveIndexRoute
  DriveUploadIndexRoute: typeof DriveUploadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/': {
      id: '/drive/'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/upload/': {
      id: '/drive/upload/'
      path: '/drive/upload'
      fullPath: '/drive/upload'
      preLoaderRoute: typeof DriveUploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriveIndexRoute: DriveIndexRoute,
  DriveUploadIndexRoute: DriveUploadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
